---
title: "Scalable and Efficient MLP-based  Fully Parameterised Quantile for Probabilistic Power Forecasting"
date: 2024-07-02
author:
  - name: Anthony Faustine
    orcid: 0000-0002-7838-533X
    affiliation: Center for Intelligent Power (CIP), Eaton Corporation, Dublin, Ireland
  - name: Pereira, Lucas
    url: https://www.alspereira.info/
    orcid: 0000-0002-9110-8775
    affiliation: ITI, LARSyS, Técnico Lisboa, 1049-001 Lisboa, Portugal
categories:
  - forecasting
  - probabilistic
  - machine learning
pub-info:
  reference: >-
     <strong>Anthony Faustine</strong> and Pereira, Lucas, “Scalable and Efficient MLP-based  Fully Parameterised Quantile for Probabilistic Power Forecasting,” <em>44th International Symposium on Forecasting, Dijon, France</em>  2024
  extra: >-
    Presented at the  44th International Symposium on Forecasting, Dijon, France.
  links:
    - name: PDF
      url: chaudhry-heiss-derogations.pdf
      local: true
      icon: fa-solid fa-file-pdf
    - name: Code
      url: https://github.com/andrewheiss/covid-derogations
      icon: fa-brands fa-github
pub-status: 
  status: Published
  class: info
  icon: fa-solid fa-rotate
---

## Important links

- [Paper (preprint)](chaudhry-heiss-derogations.pdf)
- [Statistical analysis notebook](https://stats.andrewheiss.com/covid-derogations/)
- [GitHub repository](https://github.com/andrewheiss/covid-derogations)


## Abstract

Industrial loads offer challenges for Non-intrusive Load Monitoring (NILM), such as phase imbalance associated with 3-phase lines. However, very little NILM research has been developed so far with this respect. This work presents a load recognition technique for NILM applying low complexity Fortesque Transform (FT). The FT decomposes the unbalanced 3-phase current waveform extracted from 3-phase aggregate power measurements to balance the given load. The 3-phases current waveform is transformed into an image-like representation using a compressedeuclidean distance matrix to improve the recognition ability further. The image representation is used as input to Convolutional Neural Network (CNN) classifier to learn the patterns of labeled data. Experimental evaluation of the industrial aggregated dataset shows that FT improves recognition performance by 5.8%, compared to the case without FT.




## BibTeX citation

```bibtex
@INPROCEEDINGS{10096324,
  author={Faustine, Anthony and Pereira, Lucas},
  booktitle={ICASSP 2023 - 2023 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)}, 
  title={Applying Symmetrical Component Transform for Industrial Appliance Classification in Non-Intrusive Load Monitoring}, 
  year={2023},
  volume={},
  number={},
  pages={1-5},
  keywords={Load monitoring;Symmetric matrices;Power measurement;Power demand;Transforms;Signal processing;Convolutional neural networks;NILM;Industrial Appliances;Three-Phase;Fortesque Transform;Symmetrical Components},
  doi={10.1109/ICASSP49357.2023.10096324}}
```
